# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pname',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
