# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160609_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_name',
            new_name='user',
        ),
    ]
