# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160609_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
    ]
